-- MySQL Script generated by MySQL Workbench
-- Sun Oct  6 16:46:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema friends
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friends
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friends` DEFAULT CHARACTER SET utf8 ;
USE `friends` ;

-- -----------------------------------------------------
-- Table `friends`.`friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`friends` ;

CREATE TABLE IF NOT EXISTS `friends`.`friends` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `picture_link` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friends`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`questions` ;

CREATE TABLE IF NOT EXISTS `friends`.`questions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friends`.`scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends`.`scores` ;

CREATE TABLE IF NOT EXISTS `friends`.`scores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT UNSIGNED NOT NULL,
  `friend_id` INT UNSIGNED NOT NULL,
  `score` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_friends_idx` (`friend_id` ASC) VISIBLE,
  INDEX `fk_questions_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_friends`
    FOREIGN KEY (`friend_id`)
    REFERENCES `friends`.`friends` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions`
    FOREIGN KEY (`question_id`)
    REFERENCES `friends`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
